//! Integration tests for the `xgboost-ffi` crate.
//!
//! ## Fixture Setup
//!
//! Before running model-dependent tests, generate XGBoost fixtures:
//!
//! ```bash
//! python tests/fixtures/generate_test_fixtures.py
//! ```
//!
//! This creates: `test_model_2f.json`, `test_stage1.json`, `test_stage2.json`,
//! and `expected_predictions.json`.
//!
//! Hand-crafted fixtures checked directly into the repo:
//! - `norm_stats.json` — normalization stats (20 features)
//! - `norm_stats_bad_length.json` — wrong-length stats (for error test)
//! - `invalid_model.json` — garbage JSON (for error test)
//!
//! ## Placement
//!
//! When `crates/xgboost-ffi/` is created, move this file to
//! `crates/xgboost-ffi/tests/integration.rs` and add `serde_json` as a
//! `[dev-dependencies]` entry in `crates/xgboost-ffi/Cargo.toml`.

use std::fs;
use std::path::{Path, PathBuf};

use xgboost_ffi::{GbtModel, TwoStageModel};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Locate the Cargo workspace root by walking up from CARGO_MANIFEST_DIR
/// until we find a Cargo.toml containing `[workspace]`.
fn workspace_root() -> PathBuf {
    let mut dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    loop {
        let cargo_toml = dir.join("Cargo.toml");
        if cargo_toml.exists() {
            let contents = fs::read_to_string(&cargo_toml).unwrap();
            if contents.contains("[workspace]") {
                return dir;
            }
        }
        assert!(dir.pop(), "Could not find workspace root");
    }
}

fn fixture_path(name: &str) -> PathBuf {
    workspace_root().join("tests").join("fixtures").join(name)
}

/// Assert two f32 values are approximately equal within a tolerance.
fn assert_approx_eq(actual: f32, expected: f32, tol: f32) {
    assert!(
        (actual - expected).abs() < tol,
        "expected {expected} ± {tol}, got {actual} (diff = {})",
        (actual - expected).abs()
    );
}

/// Load the expected predictions fixture (generated by Python script).
fn load_expected_predictions() -> serde_json::Value {
    let path = fixture_path("expected_predictions.json");
    let data = fs::read_to_string(&path).unwrap_or_else(|_| {
        panic!(
            "Missing fixture: {}\nRun: python tests/fixtures/generate_test_fixtures.py",
            path.display()
        )
    });
    serde_json::from_str(&data).unwrap()
}

// ===========================================================================
// T1 / T2: GbtModel — loading and lifecycle
// ===========================================================================

#[test]
fn test_load_model_from_json_file() {
    let path = fixture_path("test_model_2f.json");
    let model = GbtModel::load(&path).unwrap();
    // Successful load — Drop frees the booster handle without crashing.
    drop(model);
}

#[test]
fn test_load_model_from_buffer() {
    let path = fixture_path("test_model_2f.json");
    let buf = fs::read(&path).unwrap();
    let model = GbtModel::load_from_buffer(&buf).unwrap();
    drop(model);
}

#[test]
fn test_load_from_file_and_buffer_produce_identical_predictions() {
    let path = fixture_path("test_model_2f.json");
    let buf = fs::read(&path).unwrap();

    let model_file = GbtModel::load(&path).unwrap();
    let model_buf = GbtModel::load_from_buffer(&buf).unwrap();

    let features = [0.5f32, 0.5];
    let p_file = model_file.predict(&features).unwrap();
    let p_buf = model_buf.predict(&features).unwrap();
    assert_approx_eq(p_file, p_buf, 1e-7);
}

// ===========================================================================
// T3: GbtModel::predict — single sample
// ===========================================================================

#[test]
fn test_predict_single_known_inputs_match_python() {
    let model = GbtModel::load(&fixture_path("test_model_2f.json")).unwrap();
    let expected = load_expected_predictions();
    let vectors = expected["2f_model"]["test_vectors"].as_array().unwrap();
    let preds = expected["2f_model"]["predictions"].as_array().unwrap();

    for (i, (vec_json, exp_json)) in vectors.iter().zip(preds.iter()).enumerate() {
        let features: Vec<f32> = vec_json
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap() as f32)
            .collect();
        let expected_p = exp_json.as_f64().unwrap() as f32;
        let actual_p = model.predict(&features).unwrap();
        assert_approx_eq(actual_p, expected_p, 1e-6);
        // Annotate failures with vector index for easier debugging
        assert!(
            (actual_p - expected_p).abs() < 1e-6,
            "Vector {i}: expected {expected_p}, got {actual_p}"
        );
    }
}

#[test]
fn test_predict_returns_probability_in_unit_interval() {
    let model = GbtModel::load(&fixture_path("test_model_2f.json")).unwrap();
    let test_inputs: &[&[f32]] = &[
        &[0.5, 0.5],
        &[-1.0, 1.0],
        &[0.0, 0.0],
        &[10.0, -10.0],
        &[-5.0, -5.0],
        &[100.0, 100.0],
        &[-100.0, -100.0],
    ];
    for features in test_inputs {
        let p = model.predict(features).unwrap();
        assert!(
            (0.0..=1.0).contains(&p),
            "Probability {p} out of [0, 1] for features {features:?}"
        );
    }
}

// ===========================================================================
// T4: GbtModel::predict_batch
// ===========================================================================

#[test]
fn test_predict_batch_matches_individual_predictions() {
    let model = GbtModel::load(&fixture_path("test_model_2f.json")).unwrap();

    let samples: [[f32; 2]; 3] = [[0.5, 0.5], [-1.0, 1.0], [0.0, 0.0]];
    let flat: Vec<f32> = samples.iter().flat_map(|s| s.iter().copied()).collect();

    let batch = model.predict_batch(&flat, 3, 2).unwrap();
    assert_eq!(batch.len(), 3);

    for (i, sample) in samples.iter().enumerate() {
        let individual = model.predict(sample.as_slice()).unwrap();
        assert_approx_eq(
            batch[i],
            individual,
            1e-7,
        );
    }
}

#[test]
fn test_predict_batch_single_sample() {
    let model = GbtModel::load(&fixture_path("test_model_2f.json")).unwrap();
    let features = [0.5f32, 0.5];

    let batch = model.predict_batch(&features, 1, 2).unwrap();
    let single = model.predict(&features).unwrap();

    assert_eq!(batch.len(), 1);
    assert_approx_eq(batch[0], single, 1e-7);
}

#[test]
fn test_predict_batch_returns_correct_length() {
    let model = GbtModel::load(&fixture_path("test_model_2f.json")).unwrap();
    let n = 7;
    let features: Vec<f32> = vec![0.0; n * 2];
    let batch = model.predict_batch(&features, n, 2).unwrap();
    assert_eq!(batch.len(), n);
}

// ===========================================================================
// T5: TwoStageModel::normalize
// ===========================================================================
//
// norm_stats.json:
//   mean = [1.0, -0.5, 0.0, 0.25, -1.0, 0.5, 0,0,0,0,0,0,0,0,0,0,0,0,0, 3.0]
//   std  = [2.0,  0.5, 1.0, 0.10,  3.0, 1.5, 1,1,1,1,1,1,1,1,1,1,1,1,1, 0.0]
//
// Normalization rules:
//   z = (x - mean) / std
//   If std < 1e-10, use std = 1.0
//   If z is NaN, replace with 0.0

#[test]
fn test_normalize_basic_z_score() {
    let model = TwoStageModel::load(
        &fixture_path("test_stage1.json"),
        &fixture_path("test_stage2.json"),
        &fixture_path("norm_stats.json"),
    )
    .unwrap();

    let raw: [f32; 20] = [
        3.0, 0.0, 0.0, 0.35, -4.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 5.0,
    ];

    let z = model.normalize(&raw);

    // z[0] = (3.0 - 1.0) / 2.0 = 1.0
    assert_approx_eq(z[0], 1.0, 1e-7);
    // z[1] = (0.0 - (-0.5)) / 0.5 = 1.0
    assert_approx_eq(z[1], 1.0, 1e-7);
    // z[2] = (0.0 - 0.0) / 1.0 = 0.0
    assert_approx_eq(z[2], 0.0, 1e-7);
    // z[3] = (0.35 - 0.25) / 0.1 = 1.0
    assert_approx_eq(z[3], 1.0, 1e-7);
    // z[4] = (-4.0 - (-1.0)) / 3.0 = -1.0
    assert_approx_eq(z[4], -1.0, 1e-7);
    // z[5] = (2.0 - 0.5) / 1.5 = 1.0
    assert_approx_eq(z[5], 1.0, 1e-7);
    // z[6..19] = (0.0 - 0.0) / 1.0 = 0.0
    for i in 6..19 {
        assert_approx_eq(z[i], 0.0, 1e-7);
    }
    // z[19]: std = 0.0 < 1e-10 → floor to 1.0
    //        (5.0 - 3.0) / 1.0 = 2.0
    assert_approx_eq(z[19], 2.0, 1e-7);
}

#[test]
fn test_normalize_zero_std_uses_floor() {
    let model = TwoStageModel::load(
        &fixture_path("test_stage1.json"),
        &fixture_path("test_stage2.json"),
        &fixture_path("norm_stats.json"),
    )
    .unwrap();

    // Feature 19 has std = 0.0 → floored to 1.0
    let mut raw = [0.0f32; 20];
    raw[19] = 7.0;
    let z = model.normalize(&raw);

    // z[19] = (7.0 - 3.0) / 1.0 = 4.0
    assert_approx_eq(z[19], 4.0, 1e-7);

    // Also verify a non-zero-std feature is computed normally
    // z[0] = (0.0 - 1.0) / 2.0 = -0.5
    assert_approx_eq(z[0], -0.5, 1e-7);
}

#[test]
fn test_normalize_nan_input_produces_zero() {
    let model = TwoStageModel::load(
        &fixture_path("test_stage1.json"),
        &fixture_path("test_stage2.json"),
        &fixture_path("norm_stats.json"),
    )
    .unwrap();

    let raw = [f32::NAN; 20];
    let z = model.normalize(&raw);

    for (i, &val) in z.iter().enumerate() {
        assert_eq!(val, 0.0, "z[{i}] should be 0.0 for NaN input, got {val}");
    }
}

#[test]
fn test_normalize_all_zeros_input() {
    let model = TwoStageModel::load(
        &fixture_path("test_stage1.json"),
        &fixture_path("test_stage2.json"),
        &fixture_path("norm_stats.json"),
    )
    .unwrap();

    let raw = [0.0f32; 20];
    let z = model.normalize(&raw);

    // z[i] = (0.0 - mean[i]) / std[i]
    // z[0] = (0.0 - 1.0) / 2.0 = -0.5
    assert_approx_eq(z[0], -0.5, 1e-7);
    // z[1] = (0.0 - (-0.5)) / 0.5 = 1.0
    assert_approx_eq(z[1], 1.0, 1e-7);
    // z[2] = (0.0 - 0.0) / 1.0 = 0.0
    assert_approx_eq(z[2], 0.0, 1e-7);
    // z[3] = (0.0 - 0.25) / 0.1 = -2.5
    assert_approx_eq(z[3], -2.5, 1e-7);
    // z[4] = (0.0 - (-1.0)) / 3.0 ≈ 0.3333
    assert_approx_eq(z[4], 1.0 / 3.0, 1e-6);
    // z[5] = (0.0 - 0.5) / 1.5 ≈ -0.3333
    assert_approx_eq(z[5], -1.0 / 3.0, 1e-6);
    // z[19] = (0.0 - 3.0) / 1.0 = -3.0  (std floored)
    assert_approx_eq(z[19], -3.0, 1e-7);
}

#[test]
fn test_normalize_preserves_sign() {
    let model = TwoStageModel::load(
        &fixture_path("test_stage1.json"),
        &fixture_path("test_stage2.json"),
        &fixture_path("norm_stats.json"),
    )
    .unwrap();

    // raw[0] < mean[0] → z[0] negative
    let mut raw = [0.0f32; 20];
    raw[0] = -1.0;
    let z = model.normalize(&raw);
    // z[0] = (-1.0 - 1.0) / 2.0 = -1.0
    assert!(z[0] < 0.0, "z[0] should be negative for raw < mean");
    assert_approx_eq(z[0], -1.0, 1e-7);

    // raw[0] > mean[0] → z[0] positive
    raw[0] = 5.0;
    let z = model.normalize(&raw);
    // z[0] = (5.0 - 1.0) / 2.0 = 2.0
    assert!(z[0] > 0.0, "z[0] should be positive for raw > mean");
    assert_approx_eq(z[0], 2.0, 1e-7);
}

// ===========================================================================
// T6: TwoStageModel::predict — signal logic
// ===========================================================================
//
// Signal rules:
//   P(directional) < threshold (0.50)              → signal = 0 (HOLD)
//   P(directional) ≥ 0.50 AND P(long) > 0.50      → signal = +1 (LONG)
//   P(directional) ≥ 0.50 AND P(long) ≤ 0.50      → signal = -1 (SHORT)

#[test]
fn test_predict_hold_when_below_threshold() {
    let model = TwoStageModel::load(
        &fixture_path("test_stage1.json"),
        &fixture_path("test_stage2.json"),
        &fixture_path("norm_stats.json"),
    )
    .unwrap();

    let expected = load_expected_predictions();
    let hold_features: Vec<f32> = expected["signals"]["hold"]["raw_features"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap() as f32)
        .collect();

    let raw: [f32; 20] = hold_features
        .try_into()
        .expect("hold features should have exactly 20 elements");
    let signal = model.predict(&raw).unwrap();
    assert_eq!(signal, 0, "Expected HOLD (0) when P(directional) < 0.50");
}

#[test]
fn test_predict_long_signal() {
    let model = TwoStageModel::load(
        &fixture_path("test_stage1.json"),
        &fixture_path("test_stage2.json"),
        &fixture_path("norm_stats.json"),
    )
    .unwrap();

    let expected = load_expected_predictions();
    let long_features: Vec<f32> = expected["signals"]["long"]["raw_features"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap() as f32)
        .collect();

    let raw: [f32; 20] = long_features
        .try_into()
        .expect("long features should have exactly 20 elements");
    let signal = model.predict(&raw).unwrap();
    assert_eq!(
        signal, 1,
        "Expected LONG (+1) when P(directional) > 0.50 and P(long) > 0.50"
    );
}

#[test]
fn test_predict_short_signal() {
    let model = TwoStageModel::load(
        &fixture_path("test_stage1.json"),
        &fixture_path("test_stage2.json"),
        &fixture_path("norm_stats.json"),
    )
    .unwrap();

    let expected = load_expected_predictions();
    let short_features: Vec<f32> = expected["signals"]["short"]["raw_features"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap() as f32)
        .collect();

    let raw: [f32; 20] = short_features
        .try_into()
        .expect("short features should have exactly 20 elements");
    let signal = model.predict(&raw).unwrap();
    assert_eq!(
        signal, -1,
        "Expected SHORT (-1) when P(directional) > 0.50 and P(long) <= 0.50"
    );
}

// ===========================================================================
// T6 (continued): predict_detailed — intermediate values
// ===========================================================================

#[test]
fn test_predict_detailed_hold_has_no_p_long() {
    let model = TwoStageModel::load(
        &fixture_path("test_stage1.json"),
        &fixture_path("test_stage2.json"),
        &fixture_path("norm_stats.json"),
    )
    .unwrap();

    let expected = load_expected_predictions();
    let hold_features: Vec<f32> = expected["signals"]["hold"]["raw_features"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap() as f32)
        .collect();

    let raw: [f32; 20] = hold_features.try_into().unwrap();
    let detail = model.predict_detailed(&raw).unwrap();

    assert!(
        detail.p_directional < 0.50,
        "p_directional should be < 0.50 for HOLD, got {}",
        detail.p_directional
    );
    assert!(
        detail.p_long.is_none(),
        "p_long should be None when filtered by Stage 1 (p_dir < 0.50)"
    );
    assert_eq!(detail.signal, 0);
}

#[test]
fn test_predict_detailed_long_has_p_long() {
    let model = TwoStageModel::load(
        &fixture_path("test_stage1.json"),
        &fixture_path("test_stage2.json"),
        &fixture_path("norm_stats.json"),
    )
    .unwrap();

    let expected = load_expected_predictions();
    let long_features: Vec<f32> = expected["signals"]["long"]["raw_features"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap() as f32)
        .collect();

    let raw: [f32; 20] = long_features.try_into().unwrap();
    let detail = model.predict_detailed(&raw).unwrap();

    assert!(
        detail.p_directional > 0.50,
        "p_directional should be > 0.50 for LONG, got {}",
        detail.p_directional
    );
    assert!(
        detail.p_long.is_some(),
        "p_long should be Some when Stage 1 passes"
    );
    assert!(
        detail.p_long.unwrap() > 0.50,
        "p_long should be > 0.50 for LONG, got {}",
        detail.p_long.unwrap()
    );
    assert_eq!(detail.signal, 1);
}

#[test]
fn test_predict_detailed_short_has_p_long_below_half() {
    let model = TwoStageModel::load(
        &fixture_path("test_stage1.json"),
        &fixture_path("test_stage2.json"),
        &fixture_path("norm_stats.json"),
    )
    .unwrap();

    let expected = load_expected_predictions();
    let short_features: Vec<f32> = expected["signals"]["short"]["raw_features"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap() as f32)
        .collect();

    let raw: [f32; 20] = short_features.try_into().unwrap();
    let detail = model.predict_detailed(&raw).unwrap();

    assert!(
        detail.p_directional > 0.50,
        "p_directional should be > 0.50 for SHORT, got {}",
        detail.p_directional
    );
    assert!(
        detail.p_long.is_some(),
        "p_long should be Some when Stage 1 passes"
    );
    assert!(
        detail.p_long.unwrap() <= 0.50,
        "p_long should be <= 0.50 for SHORT, got {}",
        detail.p_long.unwrap()
    );
    assert_eq!(detail.signal, -1);
}

// ===========================================================================
// T7: Error handling
// ===========================================================================

#[test]
fn test_load_nonexistent_file_returns_error() {
    let result = GbtModel::load(Path::new("/nonexistent/path/model.json"));
    assert!(
        result.is_err(),
        "Loading a non-existent file should return Err"
    );
}

#[test]
fn test_load_invalid_model_file_returns_error() {
    let result = GbtModel::load(&fixture_path("invalid_model.json"));
    assert!(
        result.is_err(),
        "Loading an invalid model file should return Err"
    );
}

#[test]
fn test_load_from_buffer_empty_returns_error() {
    let result = GbtModel::load_from_buffer(&[]);
    assert!(
        result.is_err(),
        "Loading from an empty buffer should return Err"
    );
}

#[test]
fn test_load_from_buffer_garbage_returns_error() {
    let garbage: Vec<u8> = b"this is not a valid xgboost model".to_vec();
    let result = GbtModel::load_from_buffer(&garbage);
    assert!(
        result.is_err(),
        "Loading from garbage buffer should return Err"
    );
}

// ===========================================================================
// Additional: TwoStageModel loading and validation
// ===========================================================================

#[test]
fn test_two_stage_model_load_succeeds() {
    let result = TwoStageModel::load(
        &fixture_path("test_stage1.json"),
        &fixture_path("test_stage2.json"),
        &fixture_path("norm_stats.json"),
    );
    assert!(result.is_ok(), "TwoStageModel should load from valid fixtures");
}

#[test]
fn test_two_stage_model_load_bad_norm_stats_returns_error() {
    let result = TwoStageModel::load(
        &fixture_path("test_stage1.json"),
        &fixture_path("test_stage2.json"),
        &fixture_path("norm_stats_bad_length.json"),
    );
    assert!(
        result.is_err(),
        "Should reject norm_stats with wrong number of elements (expected 20, got 3)"
    );
}

#[test]
fn test_two_stage_model_load_nonexistent_norm_stats_returns_error() {
    let result = TwoStageModel::load(
        &fixture_path("test_stage1.json"),
        &fixture_path("test_stage2.json"),
        Path::new("/nonexistent/norm_stats.json"),
    );
    assert!(
        result.is_err(),
        "Should return Err when norm_stats file does not exist"
    );
}

#[test]
fn test_two_stage_model_load_nonexistent_stage1_returns_error() {
    let result = TwoStageModel::load(
        Path::new("/nonexistent/stage1.json"),
        &fixture_path("test_stage2.json"),
        &fixture_path("norm_stats.json"),
    );
    assert!(
        result.is_err(),
        "Should return Err when stage1 model file does not exist"
    );
}
